plugins {
    id 'java'
    id 'maven-publish'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

group = 'com.aresstack'
version = '0.1.0-beta.4'

test {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
        events 'passed', 'failed', 'skipped'
    }
}

compileJava.options.encoding = 'UTF-8'
compileTestJava.options.encoding = 'UTF-8'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.graalvm.sdk:graal-sdk:21.2.0'
    implementation 'org.graalvm.js:js:21.2.0'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            artifactId = 'win-proxy-java'
        }
    }
}
